eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    feignapi:
      path: /feign/**
      serviceId: eureka-feign-client
    hiclient:
      path: /hi/**
      serviceId: eureka-client